### PR TITLE
Enable windows and osx

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
We probably need to package https://formulae.brew.sh/formula/argp-standalone for osx.  There is an existing package here https://anaconda.org/HCC/argp-standalone/files

**Comment by davidbrochart** [comment]
Thanks @mariusvniekerk, I will package `argp`.

**Comment by davidbrochart** [comment]
So I guess I need to create a GitHub repository from the archive, as there is not license file in https://www.lysator.liu.se/~nisse/misc/argp-standalone-1.3.tar.gz.

**Comment by wolfv** [comment]
You can add a license file in the recipe-directory. Just put it in there and use teh filename in license_file and that works :)

**Comment by wolfv** [comment]
You'll also need to patch in the `endian.h`. If you want, I can do it.

**Comment by davidbrochart** [comment]
You mean, just put it in the `include` directory?

**Comment by davidbrochart** [comment]
I see, in `index_read.c`, let me do it.

**Comment by davidbrochart** [comment]
I guess we must specify `-largp` for OSX?

```
x86_64-apple-darwin13.4.0-clang  -o src/zck src/zck.p/zck.c.o src/zck.p/util_common.c.o -L$PREFIX/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/zchunk-1.1.7 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib src/lib/libzck.1.dylib -Wl,-rpath,@loader_path/lib
Undefined symbols for architecture x86_64:
  "_argp_parse", referenced from:
      _main in zck.c.o
  "_argp_usage", referenced from:
      _parse_opt in zck.c.o
```

**Comment by davidbrochart** [comment]
Not sure why `libcurl` is not found on Windows:
```
meson.build:29:0: ERROR: Dependency "libcurl" not found, tried pkgconfig and cmake
```

**Comment by davidbrochart** [comment]
I'm putting Windows on hold for now, we can already have OSX in #4.

**Comment by wolfv** [comment]
@davidbrochart finally we've got `zchunk` on Windows: https://github.com/conda-forge/zchunk-feedstock/pull/18 :)

**Pull request closed without merging**
